### ISSUE TITLE
The debug information is not shown in PHP version 7.4

### ISSUE THREAD

**Issue by Chrono79** [codewars/phpunit-codewars#1]
Sorry if it doesn't go here. There are some katas that have enabled 7.4 where you can't see the debug information, like [this one](https://www.codewars.com/kata/56c5847f27be2c3db20009c3) it only shows a collapsed Details link and when you click there it shows something like this: /workspace/default/tests/ExampleTest.php:6

Please, check.

**Comment by kazk** [comment]
`Details` contain the filtered stacktrace.

https://github.com/codewars/phpunit-codewars/blob/87964889d794b1608b0d4dfecd9f825c1435b917/src/CodewarsResultPrinter.php#L64
https://github.com/codewars/phpunit-codewars/blob/87964889d794b1608b0d4dfecd9f825c1435b917/src/CodewarsResultPrinter.php#L171-L186

> Details link and when you click there it shows something like this: `/workspace/default/tests/ExampleTest.php:6`

`/workspace/default/tests/ExampleTest.php:6` is where the error was thrown (assertion failure). I can remove `Details` on assertion failures to avoid confusion and rename `Details` to `Stacktrace` on other errors.

**Comment by Chrono79** [comment]
Ok, but the problem is you can't see the `echo` or `print_r` output in the console, how can you debug your code like that?

**Comment by kazk** [comment]
> @kazk Sure, take for instance [this kata](https://www.codewars.com/kata/56c5847f27be2c3db20009c3/train/php) <- link to the trainer
>
> If you write something like this:
>
> ```php
> function subtractSum($n) {
>   echo($n);
>   print_r($n);
>   var_dump($n);
>   return "something";
> }
> ```
>
> Neither of those will show in the Output panel if you choose 7.4, if you use 7.0 (unavailable in that kata, you can try in another like [Multiply](https://www.codewars.com/kata/50654ddff44f800200000004/train/php) <- also link to the trainer) it appears in a Log drop-down, given you write a proper sample test, the mock-up tests don't call the function.
>
> From https://github.com/codewars/codewars-runner-cli/issues/771#issuecomment-636413534

**Comment by kazk** [comment]
I had completely misunderstood you. I thought this was just about `Details` and didn't realize nothing is outputted. That's a bug and I'll look into it.

**Comment by kazk** [comment]
I'll close this when it's deployed.

**Comment by kazk** [comment]
Deployed

**Comment by Chrono79** [comment]
Thanks.
